// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqqwidZ2WOmSsLL6qxX5piAuzRbghi-c',
    appId: '1:503582997100:web:af846b36a073c4b0797649',
    messagingSenderId: '503582997100',
    projectId: 'flutter-cookbook-f558d',
    authDomain: 'flutter-cookbook-f558d.firebaseapp.com',
    storageBucket: 'flutter-cookbook-f558d.appspot.com',
    measurementId: 'G-PPERH3KW0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXQ9vjuQM4soc7UyBlL7KOBQDUn7_aXEM',
    appId: '1:503582997100:android:15853c12024b14be797649',
    messagingSenderId: '503582997100',
    projectId: 'flutter-cookbook-f558d',
    storageBucket: 'flutter-cookbook-f558d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXllA57-phY4xa_SC_0XNMBJgXZBmXQTc',
    appId: '1:503582997100:ios:1a9d0a74d0e7d4ce797649',
    messagingSenderId: '503582997100',
    projectId: 'flutter-cookbook-f558d',
    storageBucket: 'flutter-cookbook-f558d.appspot.com',
    androidClientId: '503582997100-2ollh277u6a5fqvju5iiu4jjstrsevc9.apps.googleusercontent.com',
    iosClientId: '503582997100-0p0850k5pblsgbln65ivmptaond9o6l7.apps.googleusercontent.com',
    iosBundleId: 'com.thebunkers.firebasecookbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXllA57-phY4xa_SC_0XNMBJgXZBmXQTc',
    appId: '1:503582997100:ios:1a9d0a74d0e7d4ce797649',
    messagingSenderId: '503582997100',
    projectId: 'flutter-cookbook-f558d',
    storageBucket: 'flutter-cookbook-f558d.appspot.com',
    androidClientId: '503582997100-2ollh277u6a5fqvju5iiu4jjstrsevc9.apps.googleusercontent.com',
    iosClientId: '503582997100-0p0850k5pblsgbln65ivmptaond9o6l7.apps.googleusercontent.com',
    iosBundleId: 'com.thebunkers.firebasecookbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQqqwidZ2WOmSsLL6qxX5piAuzRbghi-c',
    appId: '1:503582997100:web:6d409ec65b72c9d2797649',
    messagingSenderId: '503582997100',
    projectId: 'flutter-cookbook-f558d',
    authDomain: 'flutter-cookbook-f558d.firebaseapp.com',
    storageBucket: 'flutter-cookbook-f558d.appspot.com',
    measurementId: 'G-G0D6WS7LZ7',
  );

}